export const ADD_EMPLOYEE ='ADD_EMPLOYEE'
export const DELETE_EMPLOYEE ='DELETE_EMPLOYEE'
export const SET_CURRENT_EMPLOYEE='SET_CURRENT_EMPLOYEE'
export const UPDATE_EMPLOYEE='UPDATE_EMPLOYEE'
export const GET_EMPLOYEES = 'GET_EMPLOYEES'
export const EPMLOEE_LIST_SUCCESS ='EPMLOEE_LIST_SUCCESS'
export const EPMLOEE_LIST_ERROR ='EPMLOEE_LIST_ERROR'
export const EPMLOEE_LIST_LOADER='EPMLOEE_LIST_LOADER'

